const D=window.APP_DATA,L=window.APP_LOGIC,RESP=L.responsibleCatalog(D);let lastFocus=null;
let state={lang:'eu',view:'home',axis:'',axisView:'AX01',areaId:'',scope:'',objective:'',status:'',responsibleId:'',q:'',showDocs:false,selected:null};
const T={"es":{"title":"Consulta de la evaluación del IV Plan de Igualdad de Gernika-Lumo","meaning":"Significado de los estados","complete":"Cumplidas","partial":"Parcialmente cumplidas","not_started":"Sin abordar","source":"Fuente","global":"Resultado global","measures":"medidas","byAxis":"Resultados por eje","axisAnalysis":"Análisis por ejes","query":"Texto o código","axis":"Eje","scope":"Ámbito","objective":"Objetivo","status":"Resultado","responsible":"Responsable","all":"Todos","clear":"Limpiar filtros","results":"resultados","documents":"Documentos","showDocs":"Ver listado documental","hideDocs":"Ocultar listado documental","unassociated":"Sin asociación expresa en la matriz","close":"Cerrar","sources":"Fuentes y descargas","download":"Descargar","noFile":"Fuente sin fichero asociado","noResults":"No se encontraron medidas con estos filtros.","selection":"Resumen de la selección","total":"Total"},"eu":{"title":"Gernika-Lumoko IV. Berdintasun Planaren ebaluazioaren kontsulta","meaning":"Betetze-egoeren esanahia","complete":"Beteta","partial":"Partzialki beteta","not_started":"Landu gabe","source":"Iturria","global":"Emaitza orokorra","measures":"neurri","byAxis":"Emaitzak ardatzen arabera","axisAnalysis":"Ardatzen analisia","query":"Testua edo kodea","axis":"Ardatza","scope":"Eremua","objective":"Helburua","status":"Emaitza","responsible":"Arduraduna","all":"Guztiak","clear":"Iragazkiak garbitu","results":"emaitza","documents":"Dokumentuak","showDocs":"Dokumentuen zerrenda ikusi","hideDocs":"Dokumentuen zerrenda ezkutatu","unassociated":"Matrizean lotura espresurik gabe","close":"Itxi","sources":"Iturriak eta deskargak","download":"Deskargatu","noFile":"Lotutako fitxategirik gabeko iturria","noResults":"Ez da neurririk aurkitu iragazki hauekin.","selection":"Hautapenaren laburpena","total":"Guztira"}};
for(const lang of ['es','eu'])Object.assign(T[lang],window.APP_CONTENT[lang]);
const t=()=>T[state.lang],loc=m=>m[state.lang],pct=(n,d)=>d?`${(100*n/d).toFixed(1).replace('.',',')} %`:'0,0 %',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setView(v){closeDrawer();state.view=v;render()}function setLang(l){state.lang=l;document.documentElement.lang=l;render()}
function nav(){document.querySelector('#nav').innerHTML=['home','dashboard','axes','areas','search','documentation'].map(v=>`<button class="${state.view===v?'active':''}" onclick="setView('${v}')">${t()[v]}</button>`).join('');document.querySelectorAll('[data-lang]').forEach(b=>{b.classList.toggle('active',b.dataset.lang===state.lang);b.onclick=()=>setLang(b.dataset.lang)});document.querySelector('.brand strong').textContent=state.lang==='eu'?'IV. Berdintasun Plana':'IV Plan de Igualdad';document.querySelector('.brand span').textContent=state.lang==='eu'?'Gernika-Lumo · betetze-mailaren ebaluazioa':'Gernika-Lumo · evaluación de cumplimiento';document.querySelector('#nav').setAttribute('aria-label',state.lang==='eu'?'Nabigazio nagusia':'Navegación principal');document.querySelector('.lang').setAttribute('aria-label',state.lang==='eu'?'Hizkuntza':'Idioma');document.title=t().title}
function metric(s,n=D.counts[s],total=48){return `<div class="card metric ${s}"><b>${n}/${total}</b><span>${t()[s]} · ${pct(n,total)}</span></div>`}
function indexOf(c,total){return total?100*(c.complete+.5*c.partial)/total:0}
function bars(a){return `<div class="bar" aria-label="${esc(a[state.lang])}">${['complete','partial','not_started'].map(s=>`<span class="${s}" style="width:${100*a.counts[s]/a.total}%"></span>`).join('')}</div><div class="legend">${['complete','partial','not_started'].map(s=>`<span><i class="${s}"></i>${t()[s]}: ${a.counts[s]}/${a.total} · ${pct(a.counts[s],a.total)}</span>`).join('')}</div><p class="axis-index"><b>${t().rule}:</b> ${formatIndex(indexOf(a.counts,a.total))}</p>`}
function formatIndex(n){return `${n.toFixed(3).replace(/0+$/,'').replace(/\.$/,'').replace('.',',')} %`}
function home(){return `<section class="hero"><div><div class="eyebrow">Red Kuorum · ${t().sourceDate}</div><h1>${t().title}</h1><p class="lead">${t().lead}</p><p>${t().contents}</p><h2>${t().methodTitle}</h2><p>${t().what}</p></div><aside class="method"><small>${t().rule}</small><strong>${formatIndex(D.index)}</strong><p>${t().ruleText}</p></aside></section><section class="section"><h2>${t().meaning}</h2><div class="definitions"><p>${t().definition_complete}</p><p>${t().definition_partial}</p><p>${t().definition_not_started}</p></div></section>`}
function dashboard(){return `<div class="eyebrow">${t().source}: ${D.sourceDate}</div><h1>${t().global}</h1>${globalBook()}<div class="grid3">${metric('complete')}${metric('partial')}${metric('not_started')}</div><p class="note"><b>${t().rule}: ${formatIndex(D.index)}</b> ${t().ruleText}</p><section class="section"><h2>${t().byAxis}</h2><div class="axis-grid">${D.axes.map(a=>`<button class="card axis-card axis-link" onclick="openAxis('${a.id}')" aria-label="${esc(t().axes+': '+a[state.lang])}"><h3>${esc(a[state.lang])}</h3><p><b>${a.total}</b> ${t().measures}</p>${bars(a)}</button>`).join('')}</div></section>${measureMosaic()}`}
function openAxis(id){state.axisView=id;setView('axes')}
function axes(){let aid=state.axisView;let a=D.axes.find(x=>x.id===aid),ms=D.measures.filter(m=>m.axisId===aid);return `<h1>${t().axisAnalysis}</h1><div class="axis-select">${D.axes.map(x=>`<button class="${x.id===aid?'active':''}" onclick="state.axisView='${x.id}';render()">${esc(x[state.lang])}</button>`).join('')}</div><article class="panel axis-card"><h2>${esc(a[state.lang])}</h2>${bars(a)}</article><div class="state-columns section">${['complete','partial','not_started'].map(s=>`<section class="state-col ${s}"><h3>${t()[s]} · ${a.counts[s]}/${a.total} · ${pct(a.counts[s],a.total)}</h3>${ms.filter(m=>m.status===s).map(m=>miniButton(m)).join('')}</section>`).join('')}</div>`}
function miniButton(m){return `<button class="mini" onclick="openMeasure('${m.code}',this)" aria-label="${esc(m.code+' '+loc(m).measure)}"><b>${m.code}</b><br>${esc(loc(m).measure)}</button>`}
function optionList(key){return `<option value="">${t().all}</option>`+L.options(D,state,key).sort((a,b)=>a[1].localeCompare(b[1],state.lang)).map(([id,label])=>`<option value="${esc(id)}" ${state[key]===id?'selected':''}>${esc(label)}</option>`).join('')}
function applyFilter(key,value){state=L.cascade(D,state,key,value);render()}
function currentMeasures(){return L.filterMeasures(D,state,RESP)}
function summary(ms){const s=L.summarize(ms);return `<section class="selection-summary" aria-live="polite"><div><span>${t().total}</span><b>${s.total}</b></div>${['complete','partial','not_started'].map(k=>`<div class="${k}"><span>${t()[k]}</span><b>${s.counts[k]}/${s.total} · ${pct(s.counts[k],s.total)}</b></div>`).join('')}<div><span>${t().rule}</span><b>${formatIndex(s.index)}</b></div></section>`}
function search(){let ms=currentMeasures(),docs=D.documents;return `<h1>${t().searchTitle}</h1><div class="toolbar"><div class="field search"><label for="q">${t().query}</label><input id="q" value="${esc(state.q)}" oninput="state.q=this.value;updateSearch()"></div><div class="field"><label for="axis">${t().axis}</label><select id="axis" onchange="applyFilter('axis',this.value)">${optionList('axis')}</select></div><div class="field"><label for="scope">${t().scope}</label><select id="scope" onchange="applyFilter('scope',this.value)">${optionList('scope')}</select></div><div class="field"><label for="objective">${t().objective}</label><select id="objective" onchange="applyFilter('objective',this.value)">${optionList('objective')}</select></div><div class="field"><label for="status">${t().status}</label><select id="status" onchange="state.status=this.value;render()"><option value="">${t().all}</option>${['complete','partial','not_started'].map(s=>`<option value="${s}" ${state.status===s?'selected':''}>${t()[s]}</option>`).join('')}</select></div><div class="field"><label for="responsible">${t().responsible}</label><select id="responsible" onchange="state.responsibleId=this.value;render()"><option value="">${t().all}</option>${RESP.map(r=>`<option value="${r.id}" ${state.responsibleId===r.id?'selected':''}>${esc(r[state.lang])}</option>`).join('')}</select></div><button class="button secondary" onclick="clearFilters()">${t().clear}</button></div><div id="selectionSummary">${summary(ms)}</div><div class="results-head"><b id="resultCount">${ms.length} ${t().results}</b><button class="button primary" onclick="setView('documentation')">${t().documentation}</button></div><div id="results" class="results">${measureCards(ms)}</div>`}
function measureCards(ms){return ms.length?ms.map(m=>{let l=loc(m);return `<button class="measure ${m.status}" onclick="openMeasure('${m.code}',this)" aria-label="${esc(m.code+' '+l.measure)}"><span class="code">${m.code}</span><span><strong>${esc(l.measure)}</strong><span class="meta">${esc(l.axis)} · ${esc(l.scope)}<br><b>${t().objective}:</b> ${esc(l.objective)}<br><b>${t().responsible}:</b> ${esc(l.responsible).replace(/\n/g,' · ')}</span></span><span class="pill">${t()[m.status]}</span></button>`}).join(''):`<div class="empty">${t().noResults}</div>`}
function updateSearch(){if(state.view!=='search')return;let ms=currentMeasures();document.querySelector('#results').innerHTML=measureCards(ms);document.querySelector('#resultCount').textContent=`${ms.length} ${t().results}`;document.querySelector('#selectionSummary').innerHTML=summary(ms)}
function clearFilters(){Object.assign(state,{axis:'',scope:'',objective:'',status:'',responsibleId:'',q:''});render()}
function openMeasure(code,trigger){state.selected=code;lastFocus=trigger||document.activeElement;let m=D.measures.find(x=>x.code===code),l=loc(m),docs=m.documentIds.map(id=>D.documents.find(d=>d.id===id)).filter(Boolean),drawer=document.querySelector('#drawer');drawer.hidden=false;drawer.innerHTML=`<article class="sheet" role="dialog" aria-modal="true" aria-labelledby="sheet-title"><div class="sheet-head"><div><div class="eyebrow">${m.code} · ${t()[m.status]}</div><h2 id="sheet-title">${esc(l.measure)}</h2></div><button id="drawerClose" onclick="closeDrawer()" aria-label="${t().close}">✕</button></div><div class="meta">${esc(l.axis)}<br>${esc(l.scope)}</div><h3>${t().objective}</h3><p>${esc(l.objective)}</p><h3>${t().responsible}</h3><p>${esc(l.responsible).replace(/\n/g,'<br>')}</p><h3>${t().assessment}</h3><div class="assessment">${esc(l.assessment)}</div><h3>${t().sources}</h3><div class="downloads">${docs.map(d=>`<a class="download" href="${encodeURI(d.path)}" download><span>${esc(d.name)}</span><b>${t().download}</b></a>`).join('')}${l.plainSources.map(s=>`<div class="download"><span>${esc(s)}</span><span class="small">${t().noFile}</span></div>`).join('')}</div></article>`;drawer.onclick=e=>{if(e.target===drawer)closeDrawer()};document.addEventListener('keydown',escapeDrawer);requestAnimationFrame(()=>document.querySelector('#drawerClose').focus())}
function escapeDrawer(e){if(e.key==='Escape')closeDrawer()}function closeDrawer(){state.selected=null;document.querySelector('#drawer').hidden=true;document.removeEventListener('keydown',escapeDrawer);if(lastFocus&&document.contains(lastFocus))lastFocus.focus()}
function render(){nav();document.querySelector('#app').innerHTML=({home,dashboard,axes,areas,search,documentation}[state.view])();if(state.selected)openMeasure(state.selected,lastFocus)}document.documentElement.lang=state.lang;render();
