(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.APP_LOGIC=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const split=v=>String(v||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
  const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();
  function responsibleCatalog(data){const map=new Map();for(const m of data.measures){const es=split(m.es.responsible),eu=split(m.eu.responsible);es.forEach((label,i)=>{const key=norm(label);if(!map.has(key))map.set(key,{id:`RS${String(map.size+1).padStart(2,'0')}`,es:label,eu:eu[i]||label,codes:[]});const item=map.get(key);if(!item.codes.includes(m.code))item.codes.push(m.code)})}return [...map.values()].sort((a,b)=>a.es.localeCompare(b.es,'es'))}
  function cascade(data,state,key,value){const next={...state,[key]:value};if(key==='axis'){if(next.scope&&!data.measures.some(m=>(!value||m.axisId===value)&&m.scopeId===next.scope))next.scope='';if(next.objective&&!data.measures.some(m=>(!value||m.axisId===value)&&(!next.scope||m.scopeId===next.scope)&&m.objectiveId===next.objective))next.objective=''}if(key==='scope'&&next.objective&&!data.measures.some(m=>(!next.axis||m.axisId===next.axis)&&(!value||m.scopeId===value)&&m.objectiveId===next.objective))next.objective='';return next}
  function filterMeasures(data,state,catalog){const q=norm(state.q),rc=state.responsibleId?catalog.find(x=>x.id===state.responsibleId):null;return data.measures.filter(m=>{const l=m[state.lang],hay=norm([m.code,l.axis,l.scope,l.objective,l.measure,l.assessment,l.responsible].join(' '));return(!q||hay.includes(q))&&(!state.axis||m.axisId===state.axis)&&(!state.scope||m.scopeId===state.scope)&&(!state.objective||m.objectiveId===state.objective)&&(!state.status||m.status===state.status)&&(!rc||rc.codes.includes(m.code))})}
  function summarize(measures){const counts={complete:0,partial:0,not_started:0};measures.forEach(m=>counts[m.status]++);return{total:measures.length,counts,index:measures.length?100*(counts.complete+.5*counts.partial)/measures.length:0}}
  function options(data,state,key){let ms=data.measures;if(key==='scope')ms=ms.filter(m=>!state.axis||m.axisId===state.axis);if(key==='objective')ms=ms.filter(m=>(!state.axis||m.axisId===state.axis)&&(!state.scope||m.scopeId===state.scope));return [...new Map(ms.map(m=>[m[`${key}Id`],m[state.lang][key]])).entries()]}
  return{split,norm,responsibleCatalog,cascade,filterMeasures,summarize,options};
});
