function areaResults(){return RESP.map(r=>({...r,...L.summarize(D.measures.filter(m=>r.codes.includes(m.code)))}))}
function specificArea(r){return ['RS05','RS07','RS08','RS09','RS10','RS11','RS12'].includes(r.id)}
function areaExplanation(a){const c=a.counts,score=c.complete+0.5*c.partial;
  return state.lang==='es'
    ? `De ${a.total} medidas atribuidas, ${c.complete} están cumplidas, ${c.partial} parcialmente cumplidas y ${c.not_started} sin abordar. La puntuación es ${score.toString().replace('.',',')} de ${a.total} puntos posibles, equivalente al ${formatIndex(a.index)}.`
    : `Esleitutako ${a.total} neurrietatik, ${c.complete} beteta daude, ${c.partial} partzialki beteta eta ${c.not_started} landu gabe. Puntuazioa ${score.toString().replace('.',',')} da, gehienezko ${a.total} puntuetatik; hau da, ${formatIndex(a.index)}.`;
}
function areaCard(a){return `<article class="card area-card"><h3>${esc(a[state.lang])}</h3><div class="compliance-chart" role="img" aria-label="${esc(a[state.lang]+': '+formatIndex(a.index))}"><div class="compliance-track"><span style="width:${a.index}%"></span></div><b>${formatIndex(a.index)}</b></div><div class="chart-scale"><span>${formatIndex(0)}</span><span>${formatIndex(100)}</span></div><p>${areaExplanation(a)}</p><button class="button secondary" onclick="selectArea('${a.id}')">${t().viewMeasures}</button></article>`}
function selectArea(id){state.areaId=id;render();document.querySelector('#areaDetail').scrollIntoView({behavior:'smooth',block:'start'})}
function areaOverview(all){return `<section class="area-overview"><h2>${state.lang==='es'?'Cumplimiento por área municipal':'Betetze-maila udal-arloaren arabera'}</h2><div class="area-overview-scale"><span>${formatIndex(0)}</span><span>${formatIndex(50)}</span><span>${formatIndex(100)}</span></div>${all.filter(specificArea).slice().sort((a,b)=>b.index-a.index).map(a=>`<button class="area-overview-row" onclick="selectArea('${a.id}')" aria-label="${esc(a[state.lang]+': '+formatIndex(a.index)+'. '+t().viewMeasures)}"><span class="area-overview-name">${esc(a[state.lang])}<small>${a.total} ${t().measures}</small></span><span class="area-overview-track"><span style="width:${a.index}%"></span></span><b>${formatIndex(a.index)}</b></button>`).join('')}</section>`}
function areas(){const all=areaResults(),selected=all.find(r=>r.id===state.areaId);return `<h1>${t().areaTitle}</h1><p class="note">${t().areaNote}</p>${areaOverview(all)}<h2>${t().areaSpecific}</h2><div class="axis-grid">${all.filter(specificArea).map(areaCard).join('')}</div><section class="section"><h2>${t().areaOther}</h2><p>${t().areaOtherNote}</p><div class="axis-grid">${all.filter(r=>!specificArea(r)).map(areaCard).join('')}</div></section>${selected?`<section id="areaDetail" class="section"><h2>${t().areaDetail}: ${esc(selected[state.lang])}</h2>${summary(D.measures.filter(m=>selected.codes.includes(m.code)))}<div class="results">${measureCards(D.measures.filter(m=>selected.codes.includes(m.code)))}</div></section>`:''}`}
function codeLinks(codes){return codes.map(code=>`<button class="code-link" onclick="openMeasure('${code}',this)">${code}</button>`).join(' ')}
function documentation(){const linked=D.documents.filter(d=>d.associatedCodes.length).length;return `<h1>${t().docTitle}</h1><p class="note">${t().docNote}</p><section class="doc-overview"><div><b>${D.documents.length}</b><span>${t().documents}</span></div><div><b>${linked}</b><span>${state.lang==='es'?'Con medidas asociadas':'Lotutako neurriekin'}</span></div><div><b>${D.documents.length-linked}</b><span>${state.lang==='es'?'Sin asociación en la matriz':'Matrizean loturarik gabe'}</span></div></section><div class="doc-table-wrap"><table class="doc-table"><thead><tr><th>${t().documents}</th><th>${t().linked}</th></tr></thead><tbody>${D.documents.map(d=>`<tr><td><div class="doc-file"><span class="doc-format">${esc(d.path.split('.').pop().toUpperCase())}</span><a href="${encodeURI(d.path)}" download>${esc(d.name)}</a></div></td><td>${d.associatedCodes.length?D.axes.map(a=>{const codes=d.associatedCodes.filter(code=>D.measures.some(m=>m.code===code&&m.axisId===a.id));return codes.length?`<div class="doc-axis-group"><span class="doc-axis-label">${esc(a[state.lang])}</span>${codeLinks(codes)}</div>`:''}).join(''):`<span class="doc-unlinked">${state.lang==='es'?'Sin medida asociada en la matriz':'Matrizean lotutako neurririk gabe'}</span>`}</td></tr>`).join('')}</tbody></table></div>`}
function measureMosaic(){
  const symbols={complete:'✓',partial:'◐',not_started:'—'};
  const title=state.lang==='es'?`${D.measures.length} medidas de un vistazo`:`${D.measures.length} neurriak begirada batean`;
  return `<section class="section measure-mosaic" aria-labelledby="mosaic-title"><h2 id="mosaic-title">${title}</h2><div class="mosaic-legend">${Object.keys(symbols).map(s=>`<span><i class="mosaic-swatch ${s}" aria-hidden="true">${symbols[s]}</i>${t()[s]}</span>`).join('')}</div>${D.axes.map(a=>`<section class="mosaic-axis"><h3>${esc(a[state.lang])}</h3><div class="mosaic-grid">${D.measures.filter(m=>m.axisId===a.id).slice().sort((a,b)=>a.code.localeCompare(b.code,undefined,{numeric:true})).map(m=>`<button type="button" class="mosaic-tile ${m.status}" data-measure-code="${esc(m.code)}" onclick="openMeasure('${m.code}',this)" aria-label="${esc(m.code+' · '+t()[m.status]+' · '+loc(m).measure)}"><span aria-hidden="true">${symbols[m.status]}</span><b>${esc(m.code)}</b></button>`).join('')}</div></section>`).join('')}</section>`;
}
function globalBook(){
 const value=formatPercent(D.index,1),level=160*(1-D.index/100);
 return `<section class="global-book"><svg width="132" height="184" viewBox="0 0 132 184" role="img" aria-label="${esc(t().rule+': '+formatIndex(D.index))}"><defs><clipPath id="book-cover"><rect x="12" y="8" width="108" height="160" rx="9"/></clipPath></defs><rect x="12" y="8" width="108" height="160" rx="9" fill="#e7e4ea"/><rect x="12" y="${8+level}" width="108" height="${160-level}" fill="var(--purple)" clip-path="url(#book-cover)"/><path d="M23 8V158Q23 169 34 169H120" fill="none" stroke="#34243e" stroke-width="3"/><path d="M34 158H112M34 163H112" stroke="#fff" stroke-width="2"/></svg><div><span>${t().rule}</span><strong>${value}</strong><p>${state.lang==='es'?'Grado de cumplimiento del Plan':'Planaren betetze-maila'}</p></div></section>`;
}
