function areaResults(){return RESP.map(r=>({...r,...L.summarize(D.measures.filter(m=>r.codes.includes(m.code)))}))}
function specificArea(r){return ['RS05','RS07','RS08','RS09','RS10','RS11','RS12'].includes(r.id)}
function areaExplanation(a){const c=a.counts,score=c.complete+0.5*c.partial;
  return state.lang==='es'
    ? `De ${a.total} medidas atribuidas, ${c.complete} están cumplidas, ${c.partial} parcialmente cumplidas y ${c.not_started} sin abordar. La puntuación es ${score.toString().replace('.',',')} de ${a.total} puntos posibles, equivalente al ${formatIndex(a.index)}.`
    : `Esleitutako ${a.total} neurrietatik, ${c.complete} beteta daude, ${c.partial} partzialki beteta eta ${c.not_started} landu gabe. Puntuazioa ${score.toString().replace('.',',')} da, gehienezko ${a.total} puntuetatik; hau da, ${formatIndex(a.index)}.`;
}
function areaCard(a){return `<article class="card area-card"><h3>${esc(a[state.lang])}</h3><div class="compliance-chart" role="img" aria-label="${esc(a[state.lang]+': '+formatIndex(a.index))}"><div class="compliance-track"><span style="width:${a.index}%"></span></div><b>${formatIndex(a.index)}</b></div><div class="chart-scale"><span>0 %</span><span>100 %</span></div><p>${areaExplanation(a)}</p><button class="button secondary" onclick="selectArea('${a.id}')">${t().viewMeasures}</button></article>`}
function selectArea(id){state.areaId=id;render();document.querySelector('#areaDetail').scrollIntoView({behavior:'smooth',block:'start'})}
function areas(){const all=areaResults(),selected=all.find(r=>r.id===state.areaId);return `<h1>${t().areaTitle}</h1><p class="note">${t().areaNote}</p><h2>${t().areaSpecific}</h2><div class="axis-grid">${all.filter(specificArea).map(areaCard).join('')}</div><section class="section"><h2>${t().areaOther}</h2><p>${t().areaOtherNote}</p><div class="axis-grid">${all.filter(r=>!specificArea(r)).map(areaCard).join('')}</div></section>${selected?`<section id="areaDetail" class="section"><h2>${t().areaDetail}: ${esc(selected[state.lang])}</h2>${summary(D.measures.filter(m=>selected.codes.includes(m.code)))}<div class="results">${measureCards(D.measures.filter(m=>selected.codes.includes(m.code)))}</div></section>`:''}`}
function codeLinks(codes){return codes.map(code=>`<button class="code-link" onclick="openMeasure('${code}',this)">${code}</button>`).join(' ')}
function documentation(){return `<h1>${t().docTitle}</h1><p class="note">${t().docNote}</p><div class="doc-table-wrap"><table class="doc-table"><thead><tr><th>${t().documents}</th><th>${t().linked}</th></tr></thead><tbody>${D.documents.map(d=>`<tr><td><a href="${encodeURI(d.path)}" download>${esc(d.name)}</a></td><td>${d.associatedCodes.length?codeLinks(d.associatedCodes):`<span class="small">${state.lang==='es'?'Sin medida asociada en la matriz':'Matrizean lotutako neurririk gabe'}</span>`}</td></tr>`).join('')}</tbody></table></div>`}
